# -*- coding: utf-8 -*-
"""054_Parctice_Task2_UnLabeledData_KMC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e6dKNpDCkv0p1GUEfeBkss7XoUSj7AI0
"""

'''
Author: Dhruv B kakadiya

'''

# Imports
from sklearn.datasets.samples_generator import make_blobs

# Scatter plot of the data points
import matplotlib.pyplot as plt

# Using scikit-learn to perform K-Means clustering
from sklearn.cluster import KMeans
# Calculate silhouette_score
from sklearn.metrics import silhouette_score

# Import the KElbowVisualizer method
from yellowbrick.cluster import KElbowVisualizer

X, _ = make_blobs(n_samples = 100, centers = 3, n_features = 2, cluster_std = 0.2, random_state = 54)

plt.scatter(X[:, 0], X[:, -1])
plt.xlabel('X Coordinates')
plt.ylabel('Y Coordinates')
plt.show()

# Specify the number of clusters (3) and fit the data X
kmeans = KMeans(n_clusters=3, random_state=7).fit(X)

# Get the cluster centroids
kmeans.cluster_centers_

# Get the cluster labels
kmeans.labels_

# Plotting the cluster centers and the data points on a 2D plane
plt.scatter(X[:, 0], X[:, -1], c='orange', marker='*')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], c='green', marker='+')
plt.title('Data points and cluster centroids')
plt.show()

print(silhouette_score(X, kmeans.labels_))

# Instantiate a scikit-learn K-Means model
model = KMeans(random_state=7)

# Instantiate the KElbowVisualizer with the number of clusters and the metric
visualizer = KElbowVisualizer(model, k=(2,6), metric='silhouette',timings=False)

# Fit the data and visualize
visualizer.fit(X)
visualizer.poof()

